### ISSUE TITLE
xxx_cleaners

### ISSUE THREAD

**Issue by HobisPL** [152334H/DL-Art-School#18]
Hello,

I want to train another language, after a few hours of training it is average, so I would need to change "xxx_cleaners". I understand that by default it uses "english_cleaners". It is used in several files, where can I change it to make the change effective? Can I add an option to change the cleaners in the "EXAMPLE_gpt.yml" file? Another problem arises because there is no "xxx_cleaners" in the synthesis anywhere, which limits the synthesis due to the lack of symbols from another language.

**Comment by 152334H** [comment]
hi, you are talking about the `english_cleaner` that is hardcoded for use in `paired_voice_audio_dataset.py`, right?

```python
# https://github.com/152334H/DL-Art-School/blob/master/codes/data/audio/paired_voice_audio_dataset.py#L157
        self.text_cleaners = hparams.text_cleaners
```
(note that, although the CharacterTokenizer is hard-coded to use "english_cleaners", the GPT model does not use a CharacterTokenizer -- it uses BPE.)

I am not sure whether this will work, but have you tried adding a `text_cleaners` parameter to the val/train dataset configs? e.g.
```yaml
train:
  text_cleaners: ["basic_cleaners"]
```

The default cleaners are defined in the [tacotron2 folder](https://github.com/152334H/DL-Art-School/blob/master/codes/models/audio/tts/tacotron2/text/cleaners.py). They comment:
> Cleaners are transformations that run over the input text at both training and eval time.
> 
> Cleaners can be selected by passing a comma-delimited list of cleaner names as the "cleaners" hyperparameter. Some cleaners are English-specific. You'll typically want to use:
>  1. "english_cleaners" for English text
>  2. "transliteration_cleaners" for non-English text that can be transliterated to ASCII using the Unidecode library (https://pypi.python.org/pypi/Unidecode)
>  3. "basic_cleaners" if you do not want to transliterate (in this case, you should also update the symbols in symbols.py to match your data).

---

If that advice is not helpful, then I must apologise, because I have little-to-no experience with working with other languages in TTS. I assume @athu16 did not do anything complicated to improve his setup, either.
