### ISSUE TITLE
Dataset path is not resolving in Windows

### ISSUE THREAD

**Issue by tanfarou** [152334H/DL-Art-School#43]
The dataset path is not resolving; however, I can retrain on the older sets. Double checked the dataset, it has valid and train files and wavs folder.

<img width="980" alt="Screenshot 2023-02-26 234242" src="https://user-images.githubusercontent.com/111169072/221486907-1830735d-d2e6-47ba-b3f9-58dcce783b7e.png">

**Comment by 152334H** [comment]
This is not related to bad dataset path resolving (I think). This happens because of a recent PR (https://github.com/152334H/DL-Art-School/pull/40/files) to read files in UTF-8 (to account for different languages). This means that the dataset contains weird characters that are not in utf-8.
The error should probably be made more ergonomic, but for the time being could you try to check what text encoding the valid.txt file is using?

**Comment by tanfarou** [comment]
> This is not related to bad dataset path resolving (I think). This happens because of a recent PR (https://github.com/152334H/DL-Art-School/pull/40/files) to read files in UTF-8 (to account for different languages). This means that the dataset contains weird characters that are not in utf-8. The error should probably be made more ergonomic, but for the time being could you try to check what text encoding the valid.txt file is using?

Thank you! It is resolved. Valid.txt was in ANSI, and I changed it to utf-8, and it works perfectly.
